version: '3.5'
name: dev-env--shopify
services:
  node:
    build: .
    container_name: dev-env--shopify
    command: bash -c "tail -f /dev/null"
    working_dir: /usr/code
    volumes:
      - .:/usr/code
      - /usr/code/node_modules
    ports:
      - 3000:3000
