version: '3.5'
name: dev-env--shopify
services:
  node:
    build: .
    container_name: dev-env--shopify
    command: bash -c "tail -f /dev/null"
    working_dir: /usr/code
    volumes:
      - .:/usr/code
      - /usr/code/node_modules
      - /usr/code/checkout-customization/node_modules
      - /usr/code/checkout-customization/extensions/cw-order-discount/node_modules
