# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5018ae88cc6b27819719e742990825b1"
name = "checkout-customization-longlh"
handle = "checkout-customization-longlh"
application_url = "https://steps-quoted-place-bachelor.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dangstore2b.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_discounts"

[auth]
redirect_urls = [
  "https://steps-quoted-place-bachelor.trycloudflare.com/auth/callback",
  "https://steps-quoted-place-bachelor.trycloudflare.com/auth/shopify/callback",
  "https://steps-quoted-place-bachelor.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
